image: registry.axgn.se/wsic/ci-image
stages:
  - staticAnalysis
  - build
  - test

lint:
  stage: staticAnalysis
  script: make lint

analyze:
  stage: staticAnalysis
  script: make clean analyze
  allow_failure: true
  artifacts:
    paths:
      - build/reports/static-analysis
    when: always

insecure:
  stage: staticAnalysis
  script: ./ci/insecure.sh ./src

build:
  stage: build
  script: make clean build
  artifacts:
    paths:
    - build/wsic

debugBuild:
  stage: build
  script: make clean debug
  artifacts:
    paths:
      - build/wsic.debug

benchmark:
  stage: test
  script: ./ci/benchmark/benchmark.sh ./build/wsic.debug
  dependencies:
    - debugBuild
  artifacts:
    paths:
      - build/reports/benchmark/*/plot.png
      - build/reports/benchmark/*/report.txt
    when: always
