image: registry.axgn.se/wsic/ci-image
stages:
  - staticAnalysis
  - build
  - test

lint:
  stage: staticAnalysis
  script: make lint
  allow_failure: true

analyze:
  stage: staticAnalysis
  script: make clean analyze
  allow_failure: true
  artifacts:
    paths:
      - build/reports/static-analysis

build:
  stage: build
  script: make clean build
  artifacts:
    paths:
    - build/wsic

debugBuild:
  stage: build
  script: make clean debug
  artifacts:
    paths:
      - build/wsic.debug

benchmark:
  stage: test
  script: ./ci/benchmark/benchmark.sh ./build/wsic.debug
  allow_failure: false
  dependencies:
    - debugBuild
  artifacts:
    paths:
      - build/reports/benchmark

florianInsecure:
  stage: test
  script: ./test/florian/insecure.sh ./src
  allow_failure: true
