[server]
  parallelMode = "fork"
  daemon = false

[servers]
  [servers.default]
    domain = "localhost"
    rootDirectory = "www"
    port = 8080
  [servers.default2]
    domain = "localhost"
    rootDirectory = "www"
    port = 3000
