#include "response-codes.h"

string_t *http_codeToString(uint16_t code) {
  switch (code) {
  case 100:
    return string_fromBuffer(HTTP_CODE_TEXT_100);
  case 101:
    return string_fromBuffer(HTTP_CODE_TEXT_101);
  case 102:
    return string_fromBuffer(HTTP_CODE_TEXT_102);
  case 103:
    return string_fromBuffer(HTTP_CODE_TEXT_103);
  case 200:
    return string_fromBuffer(HTTP_CODE_TEXT_200);
  case 201:
    return string_fromBuffer(HTTP_CODE_TEXT_201);
  case 202:
    return string_fromBuffer(HTTP_CODE_TEXT_202);
  case 203:
    return string_fromBuffer(HTTP_CODE_TEXT_203);
  case 204:
    return string_fromBuffer(HTTP_CODE_TEXT_204);
  case 205:
    return string_fromBuffer(HTTP_CODE_TEXT_205);
  case 206:
    return string_fromBuffer(HTTP_CODE_TEXT_206);
  case 207:
    return string_fromBuffer(HTTP_CODE_TEXT_207);
  case 208:
    return string_fromBuffer(HTTP_CODE_TEXT_208);
  case 226:
    return string_fromBuffer(HTTP_CODE_TEXT_226);
  case 300:
    return string_fromBuffer(HTTP_CODE_TEXT_300);
  case 301:
    return string_fromBuffer(HTTP_CODE_TEXT_301);
  case 302:
    return string_fromBuffer(HTTP_CODE_TEXT_302);
  case 303:
    return string_fromBuffer(HTTP_CODE_TEXT_303);
  case 304:
    return string_fromBuffer(HTTP_CODE_TEXT_304);
  case 305:
    return string_fromBuffer(HTTP_CODE_TEXT_305);
  case 306:
    return string_fromBuffer(HTTP_CODE_TEXT_306);
  case 307:
    return string_fromBuffer(HTTP_CODE_TEXT_307);
  case 308:
    return string_fromBuffer(HTTP_CODE_TEXT_308);
  case 400:
    return string_fromBuffer(HTTP_CODE_TEXT_400);
  case 401:
    return string_fromBuffer(HTTP_CODE_TEXT_401);
  case 402:
    return string_fromBuffer(HTTP_CODE_TEXT_402);
  case 403:
    return string_fromBuffer(HTTP_CODE_TEXT_403);
  case 404:
    return string_fromBuffer(HTTP_CODE_TEXT_404);
  case 405:
    return string_fromBuffer(HTTP_CODE_TEXT_405);
  case 406:
    return string_fromBuffer(HTTP_CODE_TEXT_406);
  case 407:
    return string_fromBuffer(HTTP_CODE_TEXT_407);
  case 408:
    return string_fromBuffer(HTTP_CODE_TEXT_408);
  case 409:
    return string_fromBuffer(HTTP_CODE_TEXT_409);
  case 410:
    return string_fromBuffer(HTTP_CODE_TEXT_410);
  case 411:
    return string_fromBuffer(HTTP_CODE_TEXT_411);
  case 412:
    return string_fromBuffer(HTTP_CODE_TEXT_412);
  case 413:
    return string_fromBuffer(HTTP_CODE_TEXT_413);
  case 414:
    return string_fromBuffer(HTTP_CODE_TEXT_414);
  case 415:
    return string_fromBuffer(HTTP_CODE_TEXT_415);
  case 416:
    return string_fromBuffer(HTTP_CODE_TEXT_416);
  case 417:
    return string_fromBuffer(HTTP_CODE_TEXT_417);
  case 418:
    return string_fromBuffer(HTTP_CODE_TEXT_418);
  case 421:
    return string_fromBuffer(HTTP_CODE_TEXT_421);
  case 422:
    return string_fromBuffer(HTTP_CODE_TEXT_422);
  case 423:
    return string_fromBuffer(HTTP_CODE_TEXT_423);
  case 424:
    return string_fromBuffer(HTTP_CODE_TEXT_424);
  case 425:
    return string_fromBuffer(HTTP_CODE_TEXT_425);
  case 426:
    return string_fromBuffer(HTTP_CODE_TEXT_426);
  case 428:
    return string_fromBuffer(HTTP_CODE_TEXT_428);
  case 429:
    return string_fromBuffer(HTTP_CODE_TEXT_429);
  case 431:
    return string_fromBuffer(HTTP_CODE_TEXT_431);
  case 451:
    return string_fromBuffer(HTTP_CODE_TEXT_451);
  case 500:
    return string_fromBuffer(HTTP_CODE_TEXT_500);
  case 501:
    return string_fromBuffer(HTTP_CODE_TEXT_501);
  case 502:
    return string_fromBuffer(HTTP_CODE_TEXT_502);
  case 503:
    return string_fromBuffer(HTTP_CODE_TEXT_503);
  case 504:
    return string_fromBuffer(HTTP_CODE_TEXT_504);
  case 505:
    return string_fromBuffer(HTTP_CODE_TEXT_505);
  case 506:
    return string_fromBuffer(HTTP_CODE_TEXT_506);
  case 507:
    return string_fromBuffer(HTTP_CODE_TEXT_507);
  case 508:
    return string_fromBuffer(HTTP_CODE_TEXT_508);
  case 510:
    return string_fromBuffer(HTTP_CODE_TEXT_510);
  case 511:
    return string_fromBuffer(HTTP_CODE_TEXT_511);
  default:
    return string_fromBuffer(HTTP_CODE_TEXT_UNKNOWN);
  }
}
